/** DO NOT MODIFY - this is hashed and kept in the contract so it CANNOT be modified */

export default [
  { name: "Select your country", isValid: false, code: "", id: 0 },
  { name: "Afghanistan", isValid: true, code: "AF", id: 1 },
  { name: "Åland Islands", isValid: true, code: "AX", id: 2 },
  { name: "Albania", isValid: true, code: "AL", id: 3 },
  { name: "Algeria", isValid: true, code: "DZ", id: 4 },
  { name: "American Samoa", isValid: true, code: "AS", id: 5 },
  { name: "AndorrA", isValid: true, code: "AD", id: 6 },
  { name: "Angola", isValid: true, code: "AO", id: 7 },
  { name: "Anguilla", isValid: true, code: "AI", id: 8 },
  { name: "Antarctica", isValid: true, code: "AQ", id: 9 },
  { name: "Antigua and Barbuda", isValid: true, code: "AG", id: 10 },
  { name: "Argentina", isValid: true, code: "AR", id: 11 },
  { name: "Armenia", isValid: true, code: "AM", id: 12 },
  { name: "Aruba", isValid: true, code: "AW", id: 13 },
  { name: "Australia", isValid: true, code: "AU", id: 14 },
  { name: "Austria", isValid: true, code: "AT", id: 15 },
  { name: "Azerbaijan", isValid: true, code: "AZ", id: 16 },
  { name: "Bahamas", isValid: true, code: "BS", id: 17 },
  { name: "Bahrain", isValid: true, code: "BH", id: 18 },
  { name: "Bangladesh", isValid: false, code: "BD", id: 19 },
  { name: "Barbados", isValid: true, code: "BB", id: 20 },
  { name: "Belarus", isValid: true, code: "BY", id: 21 },
  { name: "Belgium", isValid: true, code: "BE", id: 22 },
  { name: "Belize", isValid: true, code: "BZ", id: 23 },
  { name: "Benin", isValid: true, code: "BJ", id: 24 },
  { name: "Bermuda", isValid: true, code: "BM", id: 25 },
  { name: "Bhutan", isValid: true, code: "BT", id: 26 },
  { name: "Bolivia", isValid: false, code: "BO", id: 27 },
  { name: "Bosnia and Herzegovina", isValid: true, code: "BA", id: 28 },
  { name: "Botswana", isValid: true, code: "BW", id: 29 },
  { name: "Bouvet Island", isValid: true, code: "BV", id: 30 },
  { name: "Brazil", isValid: true, code: "BR", id: 31 },
  { name: "British Indian Ocean Territory", isValid: true, code: "IO", id: 32 },
  { name: "Brunei Darussalam", isValid: true, code: "BN", id: 33 },
  { name: "Bulgaria", isValid: true, code: "BG", id: 34 },
  { name: "Burkina Faso", isValid: true, code: "BF", id: 35 },
  { name: "Burundi", isValid: true, code: "BI", id: 36 },
  { name: "Cambodia", isValid: true, code: "KH", id: 37 },
  { name: "Cameroon", isValid: true, code: "CM", id: 38 },
  { name: "Canada", isValid: false, code: "CA", id: 39 },
  { name: "Cape Verde", isValid: true, code: "CV", id: 40 },
  { name: "Cayman Islands", isValid: true, code: "KY", id: 41 },
  { name: "Central African Republic", isValid: true, code: "CF", id: 42 },
  { name: "Chad", isValid: true, code: "TD", id: 43 },
  { name: "Chile", isValid: true, code: "CL", id: 44 },
  { name: "China", isValid: false, code: "CN", id: 45 },
  { name: "Christmas Island", isValid: true, code: "CX", id: 46 },
  { name: "Cocos (Keeling) Islands", isValid: true, code: "CC", id: 47 },
  { name: "Colombia", isValid: true, code: "CO", id: 48 },
  { name: "Comoros", isValid: true, code: "KM", id: 49 },
  { name: "Congo", isValid: true, code: "CG", id: 50 },
  {
    name: "Congo, The Democratic Republic of the",
    isValid: true,
    code: "CD",
    id: 51,
  },
  { name: "Cook Islands", isValid: true, code: "CK", id: 52 },
  { name: "Costa Rica", isValid: true, code: "CR", id: 53 },
  { name: "Cote D'Ivoire", isValid: true, code: "CI", id: 54 },
  { name: "Croatia", isValid: true, code: "HR", id: 55 },
  { name: "Cuba", isValid: false, code: "CU", id: 56 },
  { name: "Cyprus", isValid: true, code: "CY", id: 57 },
  { name: "Czech Republic", isValid: true, code: "CZ", id: 58 },
  { name: "Denmark", isValid: true, code: "DK", id: 59 },
  { name: "Djibouti", isValid: true, code: "DJ", id: 60 },
  { name: "Dominica", isValid: true, code: "DM", id: 61 },
  { name: "Dominican Republic", isValid: true, code: "DO", id: 62 },
  { name: "Ecuador", isValid: false, code: "EC", id: 63 },
  { name: "Egypt", isValid: false, code: "EG", id: 64 },
  { name: "El Salvador", isValid: true, code: "SV", id: 65 },
  { name: "Equatorial Guinea", isValid: true, code: "GQ", id: 66 },
  { name: "Eritrea", isValid: true, code: "ER", id: 67 },
  { name: "Estonia", isValid: true, code: "EE", id: 68 },
  { name: "Ethiopia", isValid: true, code: "ET", id: 69 },
  { name: "Falkland Islands (Malvinas)", isValid: true, code: "FK", id: 70 },
  { name: "Faroe Islands", isValid: true, code: "FO", id: 71 },
  { name: "Fiji", isValid: true, code: "FJ", id: 72 },
  { name: "Finland", isValid: true, code: "FI", id: 73 },
  { name: "France", isValid: true, code: "FR", id: 74 },
  { name: "French Guiana", isValid: true, code: "GF", id: 75 },
  { name: "French Polynesia", isValid: true, code: "PF", id: 76 },
  { name: "French Southern Territories", isValid: true, code: "TF", id: 77 },
  { name: "Gabon", isValid: true, code: "GA", id: 78 },
  { name: "Gambia", isValid: true, code: "GM", id: 79 },
  { name: "Georgia", isValid: true, code: "GE", id: 80 },
  { name: "Germany", isValid: true, code: "DE", id: 81 },
  { name: "Ghana", isValid: true, code: "GH", id: 82 },
  { name: "Gibraltar", isValid: true, code: "GI", id: 83 },
  { name: "Greece", isValid: true, code: "GR", id: 84 },
  { name: "Greenland", isValid: true, code: "GL", id: 85 },
  { name: "Grenada", isValid: true, code: "GD", id: 86 },
  { name: "Guadeloupe", isValid: true, code: "GP", id: 87 },
  { name: "Guam", isValid: true, code: "GU", id: 88 },
  { name: "Guatemala", isValid: true, code: "GT", id: 89 },
  { name: "Guernsey", isValid: true, code: "GG", id: 90 },
  { name: "Guinea", isValid: true, code: "GN", id: 91 },
  { name: "Guinea-Bissau", isValid: true, code: "GW", id: 92 },
  { name: "Guyana", isValid: true, code: "GY", id: 93 },
  { name: "Haiti", isValid: true, code: "HT", id: 94 },
  {
    name: "Heard Island and Mcdonald Islands",
    isValid: true,
    code: "HM",
    id: 95,
  },
  { name: "Holy See (Vatican City State)", isValid: true, code: "VA", id: 96 },
  { name: "Honduras", isValid: true, code: "HN", id: 97 },
  { name: "Hong Kong", isValid: true, code: "HK", id: 98 },
  { name: "Hungary", isValid: true, code: "HU", id: 99 },
  { name: "Iceland", isValid: true, code: "IS", id: 100 },
  { name: "India", isValid: true, code: "IN", id: 101 },
  { name: "Indonesia", isValid: true, code: "ID", id: 102 },
  { name: "Iran, Islamic Republic Of", isValid: false, code: "IR", id: 103 },
  { name: "Iraq", isValid: true, code: "IQ", id: 104 },
  { name: "Ireland", isValid: true, code: "IE", id: 105 },
  { name: "Isle of Man", isValid: true, code: "IM", id: 106 },
  { name: "Israel", isValid: true, code: "IL", id: 107 },
  { name: "Italy", isValid: true, code: "IT", id: 108 },
  { name: "Jamaica", isValid: true, code: "JM", id: 109 },
  { name: "Japan", isValid: true, code: "JP", id: 110 },
  { name: "Jersey", isValid: true, code: "JE", id: 111 },
  { name: "Jordan", isValid: true, code: "JO", id: 112 },
  { name: "Kazakhstan", isValid: true, code: "KZ", id: 113 },
  { name: "Kenya", isValid: true, code: "KE", id: 114 },
  { name: "Kiribati", isValid: true, code: "KI", id: 115 },
  {
    name: "Korea, Democratic People'S Republic of",
    isValid: false,
    code: "KP",
    id: 116,
  },
  { name: "Korea, Republic of", isValid: true, code: "KR", id: 117 },
  { name: "Kuwait", isValid: true, code: "KW", id: 118 },
  { name: "Kyrgyzstan", isValid: false, code: "KG", id: 119 },
  {
    name: "Lao People'S Democratic Republic",
    isValid: true,
    code: "LA",
    id: 120,
  },
  { name: "Latvia", isValid: true, code: "LV", id: 121 },
  { name: "Lebanon", isValid: true, code: "LB", id: 122 },
  { name: "Lesotho", isValid: true, code: "LS", id: 123 },
  { name: "Liberia", isValid: true, code: "LR", id: 124 },
  { name: "Libyan Arab Jamahiriya", isValid: true, code: "LY", id: 125 },
  { name: "Liechtenstein", isValid: true, code: "LI", id: 126 },
  { name: "Lithuania", isValid: true, code: "LT", id: 127 },
  { name: "Luxembourg", isValid: true, code: "LU", id: 128 },
  { name: "Macao", isValid: true, code: "MO", id: 129 },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    isValid: true,
    code: "MK",
    id: 130,
  },
  { name: "Madagascar", isValid: true, code: "MG", id: 131 },
  { name: "Malawi", isValid: true, code: "MW", id: 132 },
  { name: "Malaysia", isValid: true, code: "MY", id: 133 },
  { name: "Maldives", isValid: true, code: "MV", id: 134 },
  { name: "Mali", isValid: true, code: "ML", id: 135 },
  { name: "Malta", isValid: true, code: "MT", id: 136 },
  { name: "Marshall Islands", isValid: true, code: "MH", id: 137 },
  { name: "Martinique", isValid: true, code: "MQ", id: 138 },
  { name: "Mauritania", isValid: true, code: "MR", id: 139 },
  { name: "Mauritius", isValid: true, code: "MU", id: 140 },
  { name: "Mayotte", isValid: true, code: "YT", id: 141 },
  { name: "Mexico", isValid: true, code: "MX", id: 142 },
  {
    name: "Micronesia, Federated States of",
    isValid: true,
    code: "FM",
    id: 143,
  },
  { name: "Moldova, Republic of", isValid: true, code: "MD", id: 144 },
  { name: "Monaco", isValid: true, code: "MC", id: 145 },
  { name: "Mongolia", isValid: true, code: "MN", id: 146 },
  { name: "Montserrat", isValid: true, code: "MS", id: 147 },
  { name: "Morocco", isValid: false, code: "MA", id: 148 },
  { name: "Mozambique", isValid: true, code: "MZ", id: 149 },
  { name: "Myanmar", isValid: false, code: "MM", id: 150 },
  { name: "Namibia", isValid: false, code: "NA", id: 151 },
  { name: "Nauru", isValid: true, code: "NR", id: 152 },
  { name: "Nepal", isValid: true, code: "NP", id: 153 },
  { name: "Netherlands", isValid: true, code: "NL", id: 154 },
  { name: "Netherlands Antilles", isValid: true, code: "AN", id: 155 },
  { name: "New Caledonia", isValid: true, code: "NC", id: 156 },
  { name: "New Zealand", isValid: true, code: "NZ", id: 157 },
  { name: "Nicaragua", isValid: true, code: "NI", id: 158 },
  { name: "Niger", isValid: true, code: "NE", id: 159 },
  { name: "Nigeria", isValid: true, code: "NG", id: 160 },
  { name: "Niue", isValid: true, code: "NU", id: 161 },
  { name: "Norfolk Island", isValid: true, code: "NF", id: 162 },
  { name: "Northern Mariana Islands", isValid: true, code: "MP", id: 163 },
  { name: "Norway", isValid: true, code: "NO", id: 164 },
  { name: "Oman", isValid: true, code: "OM", id: 165 },
  { name: "Pakistan", isValid: true, code: "PK", id: 166 },
  { name: "Palau", isValid: true, code: "PW", id: 167 },
  {
    name: "Palestinian Territory, Occupied",
    isValid: true,
    code: "PS",
    id: 168,
  },
  { name: "Panama", isValid: true, code: "PA", id: 169 },
  { name: "Papua New Guinea", isValid: true, code: "PG", id: 170 },
  { name: "Paraguay", isValid: true, code: "PY", id: 171 },
  { name: "Peru", isValid: true, code: "PE", id: 172 },
  { name: "Philippines", isValid: true, code: "PH", id: 173 },
  { name: "Pitcairn", isValid: true, code: "PN", id: 174 },
  { name: "Poland", isValid: true, code: "PL", id: 175 },
  { name: "Portugal", isValid: true, code: "PT", id: 176 },
  { name: "Puerto Rico", isValid: true, code: "PR", id: 177 },
  { name: "Qatar", isValid: true, code: "QA", id: 178 },
  { name: "Reunion", isValid: true, code: "RE", id: 179 },
  { name: "Romania", isValid: true, code: "RO", id: 180 },
  { name: "Russian Federation", isValid: true, code: "RU", id: 181 },
  { name: "RWANDA", isValid: true, code: "RW", id: 182 },
  { name: "Saint Helena", isValid: true, code: "SH", id: 183 },
  { name: "Saint Kitts and Nevis", isValid: true, code: "KN", id: 184 },
  { name: "Saint Lucia", isValid: true, code: "LC", id: 185 },
  { name: "Saint Pierre and Miquelon", isValid: true, code: "PM", id: 186 },
  {
    name: "Saint Vincent and the Grenadines",
    isValid: true,
    code: "VC",
    id: 187,
  },
  { name: "Samoa", isValid: true, code: "WS", id: 188 },
  { name: "San Marino", isValid: true, code: "SM", id: 189 },
  { name: "Sao Tome and Principe", isValid: true, code: "ST", id: 190 },
  { name: "Saudi Arabia", isValid: true, code: "SA", id: 191 },
  { name: "Senegal", isValid: true, code: "SN", id: 192 },
  { name: "Serbia and Montenegro", isValid: true, code: "CS", id: 193 },
  { name: "Seychelles", isValid: true, code: "SC", id: 194 },
  { name: "Sierra Leone", isValid: true, code: "SL", id: 195 },
  { name: "Singapore", isValid: true, code: "SG", id: 196 },
  { name: "Slovakia", isValid: true, code: "SK", id: 197 },
  { name: "Slovenia", isValid: true, code: "SI", id: 198 },
  { name: "Solomon Islands", isValid: true, code: "SB", id: 199 },
  { name: "Somalia", isValid: true, code: "SO", id: 200 },
  { name: "South Africa", isValid: true, code: "ZA", id: 201 },
  {
    name: "South Georgia and the South Sandwich Islands",
    isValid: true,
    code: "GS",
    id: 202,
  },
  { name: "Spain", isValid: true, code: "ES", id: 203 },
  { name: "Sri Lanka", isValid: true, code: "LK", id: 204 },
  { name: "Sudan", isValid: false, code: "SD", id: 205 },
  { name: "Suriname", isValid: true, code: "SR", id: 206 },
  { name: "Svalbard and Jan Mayen", isValid: true, code: "SJ", id: 207 },
  { name: "Swaziland", isValid: true, code: "SZ", id: 208 },
  { name: "Sweden", isValid: true, code: "SE", id: 209 },
  { name: "Switzerland", isValid: true, code: "CH", id: 210 },
  { name: "Syrian Arab Republic", isValid: false, code: "SY", id: 211 },
  { name: "Taiwan, Province of China", isValid: true, code: "TW", id: 212 },
  { name: "Tajikistan", isValid: true, code: "TJ", id: 213 },
  { name: "Tanzania, United Republic of", isValid: true, code: "TZ", id: 214 },
  { name: "Thailand", isValid: true, code: "TH", id: 215 },
  { name: "Timor-Leste", isValid: true, code: "TL", id: 216 },
  { name: "Togo", isValid: true, code: "TG", id: 217 },
  { name: "Tokelau", isValid: true, code: "TK", id: 218 },
  { name: "Tonga", isValid: true, code: "TO", id: 219 },
  { name: "Trinidad and Tobago", isValid: true, code: "TT", id: 220 },
  { name: "Tunisia", isValid: true, code: "TN", id: 221 },
  { name: "Turkey", isValid: true, code: "TR", id: 222 },
  { name: "Turkmenistan", isValid: true, code: "TM", id: 223 },
  { name: "Turks and Caicos Islands", isValid: true, code: "TC", id: 224 },
  { name: "Tuvalu", isValid: true, code: "TV", id: 225 },
  { name: "Uganda", isValid: true, code: "UG", id: 226 },
  { name: "Ukraine", isValid: true, code: "UA", id: 227 },
  { name: "United Arab Emirates", isValid: true, code: "AE", id: 228 },
  { name: "United Kingdom", isValid: true, code: "GB", id: 229 },
  { name: "United States", isValid: false, code: "US", id: 230 },
  {
    name: "United States Minor Outlying Islands",
    isValid: true,
    code: "UM",
    id: 231,
  },
  { name: "Uruguay", isValid: true, code: "UY", id: 232 },
  { name: "Uzbekistan", isValid: true, code: "UZ", id: 233 },
  { name: "Vanuatu", isValid: true, code: "VU", id: 234 },
  { name: "Venezuela", isValid: true, code: "VE", id: 235 },
  { name: "Viet Nam", isValid: true, code: "VN", id: 236 },
  { name: "Virgin Islands, British", isValid: true, code: "VG", id: 237 },
  { name: "Virgin Islands, U.S.", isValid: true, code: "VI", id: 238 },
  { name: "Wallis and Futuna", isValid: true, code: "WF", id: 239 },
  { name: "Western Sahara", isValid: true, code: "EH", id: 240 },
  { name: "Yemen", isValid: true, code: "YE", id: 241 },
  { name: "Zambia", isValid: true, code: "ZM", id: 242 },
  { name: "Zimbabwe", isValid: true, code: "ZW", id: 243 },
];
