export const countryData = [
  {name: 'Select your country', isValid: false, code: ''},
  {name: 'Afghanistan', isValid: true, code: 'AF'}, 
  {name: 'Åland Islands', isValid: true, code: 'AX'}, 
  {name: 'Albania', isValid: true, code: 'AL'}, 
  {name: 'Algeria', isValid: true, code: 'DZ'}, 
  {name: 'American Samoa', isValid: true, code: 'AS'}, 
  {name: 'AndorrA', isValid: true, code: 'AD'}, 
  {name: 'Angola', isValid: true, code: 'AO'}, 
  {name: 'Anguilla', isValid: true, code: 'AI'}, 
  {name: 'Antarctica', isValid: true, code: 'AQ'}, 
  {name: 'Antigua and Barbuda', isValid: true, code: 'AG'}, 
  {name: 'Argentina', isValid: true, code: 'AR'}, 
  {name: 'Armenia', isValid: true, code: 'AM'}, 
  {name: 'Aruba', isValid: true, code: 'AW'}, 
  {name: 'Australia', isValid: true, code: 'AU'}, 
  {name: 'Austria', isValid: true, code: 'AT'}, 
  {name: 'Azerbaijan', isValid: true, code: 'AZ'}, 
  {name: 'Bahamas', isValid: true, code: 'BS'}, 
  {name: 'Bahrain', isValid: true, code: 'BH'}, 
  {name: 'Bangladesh', isValid: false, code: 'BD'}, 
  {name: 'Barbados', isValid: true, code: 'BB'}, 
  {name: 'Belarus', isValid: true, code: 'BY'}, 
  {name: 'Belgium', isValid: true, code: 'BE'}, 
  {name: 'Belize', isValid: true, code: 'BZ'}, 
  {name: 'Benin', isValid: true, code: 'BJ'}, 
  {name: 'Bermuda', isValid: true, code: 'BM'}, 
  {name: 'Bhutan', isValid: true, code: 'BT'}, 
  {name: 'Bolivia', isValid: false, code: 'BO'}, 
  {name: 'Bosnia and Herzegovina', isValid: true, code: 'BA'}, 
  {name: 'Botswana', isValid: true, code: 'BW'}, 
  {name: 'Bouvet Island', isValid: true, code: 'BV'}, 
  {name: 'Brazil', isValid: true, code: 'BR'}, 
  {name: 'British Indian Ocean Territory', isValid: true, code: 'IO'}, 
  {name: 'Brunei Darussalam', isValid: true, code: 'BN'}, 
  {name: 'Bulgaria', isValid: true, code: 'BG'}, 
  {name: 'Burkina Faso', isValid: true, code: 'BF'}, 
  {name: 'Burundi', isValid: true, code: 'BI'}, 
  {name: 'Cambodia', isValid: true, code: 'KH'}, 
  {name: 'Cameroon', isValid: true, code: 'CM'}, 
  {name: 'Canada', isValid: false, code: 'CA'}, 
  {name: 'Cape Verde', isValid: true, code: 'CV'}, 
  {name: 'Cayman Islands', isValid: true, code: 'KY'}, 
  {name: 'Central African Republic', isValid: true, code: 'CF'}, 
  {name: 'Chad', isValid: true, code: 'TD'}, 
  {name: 'Chile', isValid: true, code: 'CL'}, 
  {name: 'China', isValid: false, code: 'CN'}, 
  {name: 'Christmas Island', isValid: true, code: 'CX'}, 
  {name: 'Cocos (Keeling) Islands', isValid: true, code: 'CC'}, 
  {name: 'Colombia', isValid: true, code: 'CO'}, 
  {name: 'Comoros', isValid: true, code: 'KM'}, 
  {name: 'Congo', isValid: true, code: 'CG'}, 
  {name: 'Congo, The Democratic Republic of the', isValid: true, code: 'CD'}, 
  {name: 'Cook Islands', isValid: true, code: 'CK'}, 
  {name: 'Costa Rica', isValid: true, code: 'CR'}, 
  {name: 'Cote D\'Ivoire', isValid: true, code: 'CI'}, 
  {name: 'Croatia', isValid: true, code: 'HR'}, 
  {name: 'Cuba', isValid: false, code: 'CU'}, 
  {name: 'Cyprus', isValid: true, code: 'CY'}, 
  {name: 'Czech Republic', isValid: true, code: 'CZ'}, 
  {name: 'Denmark', isValid: true, code: 'DK'}, 
  {name: 'Djibouti', isValid: true, code: 'DJ'}, 
  {name: 'Dominica', isValid: true, code: 'DM'}, 
  {name: 'Dominican Republic', isValid: true, code: 'DO'}, 
  {name: 'Ecuador', isValid: false, code: 'EC'}, 
  {name: 'Egypt', isValid: false, code: 'EG'}, 
  {name: 'El Salvador', isValid: true, code: 'SV'}, 
  {name: 'Equatorial Guinea', isValid: true, code: 'GQ'}, 
  {name: 'Eritrea', isValid: true, code: 'ER'}, 
  {name: 'Estonia', isValid: true, code: 'EE'}, 
  {name: 'Ethiopia', isValid: true, code: 'ET'}, 
  {name: 'Falkland Islands (Malvinas)', isValid: true, code: 'FK'}, 
  {name: 'Faroe Islands', isValid: true, code: 'FO'}, 
  {name: 'Fiji', isValid: true, code: 'FJ'}, 
  {name: 'Finland', isValid: true, code: 'FI'}, 
  {name: 'France', isValid: true, code: 'FR'}, 
  {name: 'French Guiana', isValid: true, code: 'GF'}, 
  {name: 'French Polynesia', isValid: true, code: 'PF'}, 
  {name: 'French Southern Territories', isValid: true, code: 'TF'}, 
  {name: 'Gabon', isValid: true, code: 'GA'}, 
  {name: 'Gambia', isValid: true, code: 'GM'}, 
  {name: 'Georgia', isValid: true, code: 'GE'}, 
  {name: 'Germany', isValid: true, code: 'DE'}, 
  {name: 'Ghana', isValid: true, code: 'GH'}, 
  {name: 'Gibraltar', isValid: true, code: 'GI'}, 
  {name: 'Greece', isValid: true, code: 'GR'}, 
  {name: 'Greenland', isValid: true, code: 'GL'}, 
  {name: 'Grenada', isValid: true, code: 'GD'}, 
  {name: 'Guadeloupe', isValid: true, code: 'GP'}, 
  {name: 'Guam', isValid: true, code: 'GU'}, 
  {name: 'Guatemala', isValid: true, code: 'GT'}, 
  {name: 'Guernsey', isValid: true, code: 'GG'}, 
  {name: 'Guinea', isValid: true, code: 'GN'}, 
  {name: 'Guinea-Bissau', isValid: true, code: 'GW'}, 
  {name: 'Guyana', isValid: true, code: 'GY'}, 
  {name: 'Haiti', isValid: true, code: 'HT'}, 
  {name: 'Heard Island and Mcdonald Islands', isValid: true, code: 'HM'}, 
  {name: 'Holy See (Vatican City State)', isValid: true, code: 'VA'}, 
  {name: 'Honduras', isValid: true, code: 'HN'}, 
  {name: 'Hong Kong', isValid: true, code: 'HK'}, 
  {name: 'Hungary', isValid: true, code: 'HU'}, 
  {name: 'Iceland', isValid: true, code: 'IS'}, 
  {name: 'India', isValid: true, code: 'IN'}, 
  {name: 'Indonesia', isValid: true, code: 'ID'}, 
  {name: 'Iran, Islamic Republic Of', isValid: false, code: 'IR'}, 
  {name: 'Iraq', isValid: true, code: 'IQ'}, 
  {name: 'Ireland', isValid: true, code: 'IE'}, 
  {name: 'Isle of Man', isValid: true, code: 'IM'}, 
  {name: 'Israel', isValid: true, code: 'IL'}, 
  {name: 'Italy', isValid: true, code: 'IT'}, 
  {name: 'Jamaica', isValid: true, code: 'JM'}, 
  {name: 'Japan', isValid: true, code: 'JP'}, 
  {name: 'Jersey', isValid: true, code: 'JE'}, 
  {name: 'Jordan', isValid: true, code: 'JO'}, 
  {name: 'Kazakhstan', isValid: true, code: 'KZ'}, 
  {name: 'Kenya', isValid: true, code: 'KE'}, 
  {name: 'Kiribati', isValid: true, code: 'KI'}, 
  {name: 'Korea, Democratic People\'S Republic of', isValid: false, code: 'KP'}, 
  {name: 'Korea, Republic of', isValid: true, code: 'KR'}, 
  {name: 'Kuwait', isValid: true, code: 'KW'}, 
  {name: 'Kyrgyzstan', isValid: false, code: 'KG'}, 
  {name: 'Lao People\'S Democratic Republic', isValid: true, code: 'LA'}, 
  {name: 'Latvia', isValid: true, code: 'LV'}, 
  {name: 'Lebanon', isValid: true, code: 'LB'}, 
  {name: 'Lesotho', isValid: true, code: 'LS'}, 
  {name: 'Liberia', isValid: true, code: 'LR'}, 
  {name: 'Libyan Arab Jamahiriya', isValid: true, code: 'LY'}, 
  {name: 'Liechtenstein', isValid: true, code: 'LI'}, 
  {name: 'Lithuania', isValid: true, code: 'LT'}, 
  {name: 'Luxembourg', isValid: true, code: 'LU'}, 
  {name: 'Macao', isValid: true, code: 'MO'}, 
  {name: 'Macedonia, The Former Yugoslav Republic of', isValid: true, code: 'MK'}, 
  {name: 'Madagascar', isValid: true, code: 'MG'}, 
  {name: 'Malawi', isValid: true, code: 'MW'}, 
  {name: 'Malaysia', isValid: true, code: 'MY'}, 
  {name: 'Maldives', isValid: true, code: 'MV'}, 
  {name: 'Mali', isValid: true, code: 'ML'}, 
  {name: 'Malta', isValid: true, code: 'MT'}, 
  {name: 'Marshall Islands', isValid: true, code: 'MH'}, 
  {name: 'Martinique', isValid: true, code: 'MQ'}, 
  {name: 'Mauritania', isValid: true, code: 'MR'}, 
  {name: 'Mauritius', isValid: true, code: 'MU'}, 
  {name: 'Mayotte', isValid: true, code: 'YT'}, 
  {name: 'Mexico', isValid: true, code: 'MX'}, 
  {name: 'Micronesia, Federated States of', isValid: true, code: 'FM'}, 
  {name: 'Moldova, Republic of', isValid: true, code: 'MD'}, 
  {name: 'Monaco', isValid: true, code: 'MC'}, 
  {name: 'Mongolia', isValid: true, code: 'MN'}, 
  {name: 'Montserrat', isValid: true, code: 'MS'}, 
  {name: 'Morocco', isValid: false, code: 'MA'}, 
  {name: 'Mozambique', isValid: true, code: 'MZ'}, 
  {name: 'Myanmar', isValid: false, code: 'MM'}, 
  {name: 'Namibia', isValid: false, code: 'NA'}, 
  {name: 'Nauru', isValid: true, code: 'NR'}, 
  {name: 'Nepal', isValid: true, code: 'NP'}, 
  {name: 'Netherlands', isValid: true, code: 'NL'}, 
  {name: 'Netherlands Antilles', isValid: true, code: 'AN'}, 
  {name: 'New Caledonia', isValid: true, code: 'NC'}, 
  {name: 'New Zealand', isValid: true, code: 'NZ'}, 
  {name: 'Nicaragua', isValid: true, code: 'NI'}, 
  {name: 'Niger', isValid: true, code: 'NE'}, 
  {name: 'Nigeria', isValid: true, code: 'NG'}, 
  {name: 'Niue', isValid: true, code: 'NU'}, 
  {name: 'Norfolk Island', isValid: true, code: 'NF'}, 
  {name: 'Northern Mariana Islands', isValid: true, code: 'MP'}, 
  {name: 'Norway', isValid: true, code: 'NO'}, 
  {name: 'Oman', isValid: true, code: 'OM'}, 
  {name: 'Pakistan', isValid: true, code: 'PK'}, 
  {name: 'Palau', isValid: true, code: 'PW'}, 
  {name: 'Palestinian Territory, Occupied', isValid: true, code: 'PS'}, 
  {name: 'Panama', isValid: true, code: 'PA'}, 
  {name: 'Papua New Guinea', isValid: true, code: 'PG'}, 
  {name: 'Paraguay', isValid: true, code: 'PY'}, 
  {name: 'Peru', isValid: true, code: 'PE'}, 
  {name: 'Philippines', isValid: true, code: 'PH'}, 
  {name: 'Pitcairn', isValid: true, code: 'PN'}, 
  {name: 'Poland', isValid: true, code: 'PL'}, 
  {name: 'Portugal', isValid: true, code: 'PT'}, 
  {name: 'Puerto Rico', isValid: true, code: 'PR'}, 
  {name: 'Qatar', isValid: true, code: 'QA'}, 
  {name: 'Reunion', isValid: true, code: 'RE'}, 
  {name: 'Romania', isValid: true, code: 'RO'}, 
  {name: 'Russian Federation', isValid: true, code: 'RU'}, 
  {name: 'RWANDA', isValid: true, code: 'RW'}, 
  {name: 'Saint Helena', isValid: true, code: 'SH'}, 
  {name: 'Saint Kitts and Nevis', isValid: true, code: 'KN'}, 
  {name: 'Saint Lucia', isValid: true, code: 'LC'}, 
  {name: 'Saint Pierre and Miquelon', isValid: true, code: 'PM'}, 
  {name: 'Saint Vincent and the Grenadines', isValid: true, code: 'VC'}, 
  {name: 'Samoa', isValid: true, code: 'WS'}, 
  {name: 'San Marino', isValid: true, code: 'SM'}, 
  {name: 'Sao Tome and Principe', isValid: true, code: 'ST'}, 
  {name: 'Saudi Arabia', isValid: true, code: 'SA'}, 
  {name: 'Senegal', isValid: true, code: 'SN'}, 
  {name: 'Serbia and Montenegro', isValid: true, code: 'CS'}, 
  {name: 'Seychelles', isValid: true, code: 'SC'}, 
  {name: 'Sierra Leone', isValid: true, code: 'SL'}, 
  {name: 'Singapore', isValid: true, code: 'SG'}, 
  {name: 'Slovakia', isValid: true, code: 'SK'}, 
  {name: 'Slovenia', isValid: true, code: 'SI'}, 
  {name: 'Solomon Islands', isValid: true, code: 'SB'}, 
  {name: 'Somalia', isValid: true, code: 'SO'}, 
  {name: 'South Africa', isValid: true, code: 'ZA'}, 
  {name: 'South Georgia and the South Sandwich Islands', isValid: true, code: 'GS'}, 
  {name: 'Spain', isValid: true, code: 'ES'}, 
  {name: 'Sri Lanka', isValid: true, code: 'LK'}, 
  {name: 'Sudan', isValid: false, code: 'SD'}, 
  {name: 'Suriname', isValid: true, code: 'SR'}, 
  {name: 'Svalbard and Jan Mayen', isValid: true, code: 'SJ'}, 
  {name: 'Swaziland', isValid: true, code: 'SZ'}, 
  {name: 'Sweden', isValid: true, code: 'SE'}, 
  {name: 'Switzerland', isValid: true, code: 'CH'}, 
  {name: 'Syrian Arab Republic', isValid: false, code: 'SY'}, 
  {name: 'Taiwan, Province of China', isValid: true, code: 'TW'}, 
  {name: 'Tajikistan', isValid: true, code: 'TJ'}, 
  {name: 'Tanzania, United Republic of', isValid: true, code: 'TZ'}, 
  {name: 'Thailand', isValid: true, code: 'TH'}, 
  {name: 'Timor-Leste', isValid: true, code: 'TL'}, 
  {name: 'Togo', isValid: true, code: 'TG'}, 
  {name: 'Tokelau', isValid: true, code: 'TK'}, 
  {name: 'Tonga', isValid: true, code: 'TO'}, 
  {name: 'Trinidad and Tobago', isValid: true, code: 'TT'}, 
  {name: 'Tunisia', isValid: true, code: 'TN'}, 
  {name: 'Turkey', isValid: true, code: 'TR'}, 
  {name: 'Turkmenistan', isValid: true, code: 'TM'}, 
  {name: 'Turks and Caicos Islands', isValid: true, code: 'TC'}, 
  {name: 'Tuvalu', isValid: true, code: 'TV'}, 
  {name: 'Uganda', isValid: true, code: 'UG'}, 
  {name: 'Ukraine', isValid: true, code: 'UA'}, 
  {name: 'United Arab Emirates', isValid: true, code: 'AE'}, 
  {name: 'United Kingdom', isValid: true, code: 'GB'}, 
  {name: 'United States', isValid: false, code: 'US'}, 
  {name: 'United States Minor Outlying Islands', isValid: true, code: 'UM'}, 
  {name: 'Uruguay', isValid: true, code: 'UY'}, 
  {name: 'Uzbekistan', isValid: true, code: 'UZ'}, 
  {name: 'Vanuatu', isValid: true, code: 'VU'}, 
  {name: 'Venezuela', isValid: true, code: 'VE'}, 
  {name: 'Viet Nam', isValid: true, code: 'VN'}, 
  {name: 'Virgin Islands, British', isValid: true, code: 'VG'}, 
  {name: 'Virgin Islands, U.S.', isValid: true, code: 'VI'}, 
  {name: 'Wallis and Futuna', isValid: true, code: 'WF'}, 
  {name: 'Western Sahara', isValid: true, code: 'EH'}, 
  {name: 'Yemen', isValid: true, code: 'YE'}, 
  {name: 'Zambia', isValid: true, code: 'ZM'}, 
  {name: 'Zimbabwe', isValid: true, code: 'ZW'} 
]