name: Mocked tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        id: Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install root dependencies
        run: yarn install

      - name: Start server in the background
        run: yarn start:mock &

      # Install yarn automation/ dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:3000"
          working-directory: automation
          wait-on-timeout: 120
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          # pass cypress integration test private key
          CYPRESS_INTEGRATION_TEST_MNEMONIC: ${{ secrets.CYPRESS_INTEGRATION_TEST_MNEMONIC }}
          CYPRESS_VEGA_WALLET_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_VEGA_WALLET_NAME: ${{ secrets.VEGA_WALLET_NAME }}
          CYPRESS_INFURA_ID: "4f846e79e13f44d1b51bbd7ed9edefb8"
