name: Jest

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      # https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          yarn install --frozen-lockfile
          yarn run test
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build
        run: |
          yarn run build

      # Pins to IPFS with Infura. No auth required.
      - name: Pin to IPFS
        uses: alexanderschau/ipfs-pinning-action@v1.0.0
        with:
          path_to_add: 'build' #Required
          endpoint: ${{ secrets.IPFS_ENDPOINT }} #Required
          access_token: ${{ secrets.IPFS_ACCESS_TOKEN }} #Required
          pin_name: 'github-actions-test' #Optional
